### ISSUE TITLE
Bug with parallel processing

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-fortran#88]
This might have come up before but just in case:

```bash
(rrr-axl) vince@siren:~$ cat axlf_with_2_processes.py
import axelrod_fortran as axlf
import axelrod as axl
p1 = axlf.Player('k31r')
p2 = axlf.Player('k33r')
tournament = axl.Tournament((p1, p2), turns=5)
results = tournament.play(processes=2)
print(results.payoff_matrix)
(rrr-axl) vince@siren:~$ python axlf_with_2_processes.py
Playing matches:   0%|                                                                                      | 0/3 [00:00<?, ?it/s]Process Process-3:
Traceback (most recent call last):
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/tournament.py", line 404, in _worker
    interactions = self._play_matches(chunk, build_results)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/tournament.py", line 436, in _play_matches
    match.play()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/match.py", line 188, in play
    p.reset()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod_fortran/player.py", line 139, in reset
    self._release_shared_library()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod_fortran/player.py", line 133, in _release_shared_library
    shared_library_manager.release(name, index)
  File "<string>", line 2, in release
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/managers.py", line 263, in serve_client
    res = function(*args, **kwds)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod_fortran/shared_library_manager.py", line 100, in release
    self.player_indices[name].remove(index)
KeyError: 1
^CTraceback (most recent call last):
  File "axlf_with_2_processes.py", line 6, in <module>
    results = tournament.play(processes=2)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/tournament.py", line 148, in play
    self._run_parallel(build_results=build_results, processes=processes)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/tournament.py", line 311, in _run_parallel
    self._process_done_queue(workers, done_queue, build_results)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/site-packages/axelrod/tournament.py", line 378, in _process_done_queue
    results = done_queue.get()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/vince/.conda/envs/rrr-axl/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Playing matches:  67%|████████████████████████████████████████████████████                          | 2/3 [00:13<00:06,  6.96s/it]
```

and without `processes` we get:

```bash
(rrr-axl) vince@siren:~$ cat axlf_with_no_processes.py
import axelrod_fortran as axlf
import axelrod as axl
p1 = axlf.Player('k31r')
p2 = axlf.Player('k33r')
tournament = axl.Tournament((p1, p2), turns=5)
results = tournament.play()
print(results.payoff_matrix)
(rrr-axl) vince@siren:~$ python axlf_with_no_processes.py
Playing matches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 78.31it/s]
Analysing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 91.37it/s]
[[3.0, 1.8], [3.7999999999999994, 2.2]]
```

This is not a huge problem (possibly not worth trying to fix as it deals with the shared copies of the `.so` file) but could be good to have something that overrides or at least warns if running a tournament with parallel processing?

**Comment by marcharper** [comment]
I'll take a look.

**Comment by marcharper** [comment]
I ran both scripts locally with the latest versions of both libraries and neither produced an error. Also the following works without error, four processes and three copies of every strategy.

```
import axelrod_fortran as axlf
import axelrod as axl
players = [axlf.Player(strategy) for strategy in axlf.all_strategies]
players.extend([axlf.Player(strategy) for strategy in axlf.all_strategies])
players.extend([axlf.Player(strategy) for strategy in axlf.all_strategies])
print(len(players))

tournament = axl.Tournament(players, turns=20, repetitions=10)
results = tournament.play(processes=4)
print(results.payoff_matrix)
```

Can you try again with a fresh install and confirm that you can reproduce it? If so then it may be a platform issue (I'm running Linux).

**Comment by drvinceknight** [comment]
Thanks for checking, I was running it on ubuntu, will try again next week but on OSX as the linux machine is running the revisiting experiments now which I don't want to make fall over 👍 

If it worked for you it's probably just something on that machine...

**Comment by marcharper** [comment]
@drvinceknight did you resolve the issue with this one?

**Comment by drvinceknight** [comment]
> @drvinceknight did you resolve the issue with this one?

Gosh, sorry I meant to reply: everything is indeed working fine now.
